### PR TITLE
Laravel 7 support

### LINKED ISSUE #55: PHPUnit 9
Please add PHPUnit 9 support.

### PR DESCRIPTION
**Pull request by ssfinney**
Fixes #55

### CODE REVIEW

**Comment by ssfinney** [comment]
PHP 7.4 with SETUP=lowest still failing

https://travis-ci.org/github/spinen/laravel-mail-assertions/jobs/670776901

**Comment by jimmypuckett** [comment]
That is so odd.  It is passing with other repos.  Let me know if you want to review it together.

**Comment by jimmypuckett** [comment]
@ssfinney I have been beating my head against the wall on the ClickUp repo getting the same error.  As it turns out, <5.8 may not work with php 7.4...

https://github.com/laravel/framework/issues/30737

Has to do with the changes from this RFC...

https://wiki.php.net/rfc/notice-for-non-valid-array-container

We need to discuss how we want to move forward.

**Comment by jimmypuckett** [comment]
Looks fine to merge when you are ready.

**Comment by ssfinney** [comment]
@jimmypuckett Still can't figure this one out.

**Pull request merged**
