### PR TITLE
Rename seeEmailsSent() to seeEmailCountEquals()

### LINKED ISSUE #19: Rename seeEmailsSent()
This is too easily confused with seeEmailWasSent().

Try these:

seeEmailCount()
seeEmailCountEquals()
seeEmailSentCount()

Not sure which I like best, or if there are other suggestions.

### PR DESCRIPTION
**Pull request by ssfinney**
Fixes #19

### CODE REVIEW

**Comment by jimmypuckett** [comment]
@ssfinney I think that this looks great, but I think that we should consider keeping a seeEmailsSent method that calls the seeEmailCountEquals method? We could mark the seeEmailsSent method  deprecated in the docblock.

This maybe a waste as there have been so few downloads at this time, but should we consider it?

**Comment by jimmypuckett** [comment]
@ssfinney Also, you need to update the method name in the readme.  Thanks.

**Comment by ssfinney** [comment]
@jimmypuckett I don't have a preference, so sure. What's the amount of time people typically keep deprecated methods?

Maybe we could take this change, and some of the "bigger" issues like #18 and #15, then make a new minor version (0.1.0). Also, do we need a changelog?

**Comment by ssfinney** [comment]
@jimmypuckett I've made that change

**Pull request merged**
